---
title: "Monthly report"
output: github_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path='Figs/')
```

```{r setup, include=FALSE}
# for github api
library(gh)
# for google analytics api
library(googleAnalyticsR)
library(googleAuthR)
# for markdown
library(knitr)
library(kableExtra)
# for plotting
library(ggplot2)
# for data wrangling
library(lubridate)
library(tidyverse)
# for coop metrics functions
# library(coopMetrics)
files.sources <- list.files(path = "R/", pattern = "*.R")
sapply(paste0("R/", files.sources), source)
```

## Set variables
For this report we are looking at the first 6 months of the year
```{r variables}
# cache is set to store the last year of data - must update cache if you need to go further back than a year.
begin <- as_date("2020-01-01")
end <- as_date(Sys.Date())
dateRange <- c(begin, end)
```

## Load data
```{r}
load("R/sysdata.rda")
message(paste0("Data loaded was last updated on ", cacheDate))
message(paste0("Today is ", Sys.Date()))
```

# Plot posts over time
```{r posts-total-plot}
ggplot(blogMetrics, aes(x = month, y = gh_numPostTotal)) +
  geom_line() +
  labs(title = "total posts by month", x = "month", y = "total number of posts") +
  theme_minimal()
```

```{r posts-monthly-plot}
ggplot(blogMetrics, aes(x = month, y = gh_numNewPosts)) +
  geom_bar(stat = "identity") +
  labs(title = "number of posts per month", x = "month", y = "number of posts") +
  theme_minimal()
```

```{r posts-overlay}
ggplot(blogMetrics, aes(x = month)) +
  geom_bar(aes(y = gh_numNewPosts), stat = "identity") +
  geom_line(aes(y = gh_numPostTotal)) +
  labs(title = "number of posts per month with running total", x = "month", y = "number of posts") +
  theme_minimal()
```

# Plot commits over time
```{r commits-monthly-plot}
ggplot(blogMetrics, aes(x = month, y = gh_numCommits)) +
  geom_bar(stat = "identity") +
  labs(title = "number of commits per month", x = "month", y = "number of commits") +
  theme_minimal()
```

# Plot google analytics metrics
```{r}
blogMetrics %>%
  select(month, ga_users, ga_newUsers) %>%
  ggplot(aes(x = month)) +
  geom_line(aes(y = ga_users, color = "users")) +
  geom_line(aes(y = ga_newUsers, color = "newUsers")) +
  labs(x = "month", y = "number of users") +
  theme_minimal()
```

```{r}
blogMetrics %>%
  ggplot(aes(x = month)) +
  geom_line(aes(y = ga_pageviews, color = "page views")) +
  geom_line(aes(y = ga_sessions, color = "sessions")) +
  labs(x = "month", y = "count") +
  theme_minimal()
```
